; PlatformIO Project Configuration File
;
; ESP8266 NodeMCU CP2102 + DHT Humidity Sensor + MQTT

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_port = COM16
monitor_port = COM16
lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    knolleary/PubSubClient@^2.8
